package com.zmx.mian.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zmx.mian.bean.CommodityPositionGD;
import com.zmx.mian.bean.FeedbackBean;
import com.zmx.mian.bean.Goods;
import com.zmx.mian.bean.MallTypeBean;
import com.zmx.mian.bean.StockManagementBean;
import com.zmx.mian.bean.StockManagementDetailsBean;

import com.zmx.mian.dao.CommodityPositionGDDao;
import com.zmx.mian.dao.FeedbackBeanDao;
import com.zmx.mian.dao.GoodsDao;
import com.zmx.mian.dao.MallTypeBeanDao;
import com.zmx.mian.dao.StockManagementBeanDao;
import com.zmx.mian.dao.StockManagementDetailsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commodityPositionGDDaoConfig;
    private final DaoConfig feedbackBeanDaoConfig;
    private final DaoConfig goodsDaoConfig;
    private final DaoConfig mallTypeBeanDaoConfig;
    private final DaoConfig stockManagementBeanDaoConfig;
    private final DaoConfig stockManagementDetailsBeanDaoConfig;

    private final CommodityPositionGDDao commodityPositionGDDao;
    private final FeedbackBeanDao feedbackBeanDao;
    private final GoodsDao goodsDao;
    private final MallTypeBeanDao mallTypeBeanDao;
    private final StockManagementBeanDao stockManagementBeanDao;
    private final StockManagementDetailsBeanDao stockManagementDetailsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commodityPositionGDDaoConfig = daoConfigMap.get(CommodityPositionGDDao.class).clone();
        commodityPositionGDDaoConfig.initIdentityScope(type);

        feedbackBeanDaoConfig = daoConfigMap.get(FeedbackBeanDao.class).clone();
        feedbackBeanDaoConfig.initIdentityScope(type);

        goodsDaoConfig = daoConfigMap.get(GoodsDao.class).clone();
        goodsDaoConfig.initIdentityScope(type);

        mallTypeBeanDaoConfig = daoConfigMap.get(MallTypeBeanDao.class).clone();
        mallTypeBeanDaoConfig.initIdentityScope(type);

        stockManagementBeanDaoConfig = daoConfigMap.get(StockManagementBeanDao.class).clone();
        stockManagementBeanDaoConfig.initIdentityScope(type);

        stockManagementDetailsBeanDaoConfig = daoConfigMap.get(StockManagementDetailsBeanDao.class).clone();
        stockManagementDetailsBeanDaoConfig.initIdentityScope(type);

        commodityPositionGDDao = new CommodityPositionGDDao(commodityPositionGDDaoConfig, this);
        feedbackBeanDao = new FeedbackBeanDao(feedbackBeanDaoConfig, this);
        goodsDao = new GoodsDao(goodsDaoConfig, this);
        mallTypeBeanDao = new MallTypeBeanDao(mallTypeBeanDaoConfig, this);
        stockManagementBeanDao = new StockManagementBeanDao(stockManagementBeanDaoConfig, this);
        stockManagementDetailsBeanDao = new StockManagementDetailsBeanDao(stockManagementDetailsBeanDaoConfig, this);

        registerDao(CommodityPositionGD.class, commodityPositionGDDao);
        registerDao(FeedbackBean.class, feedbackBeanDao);
        registerDao(Goods.class, goodsDao);
        registerDao(MallTypeBean.class, mallTypeBeanDao);
        registerDao(StockManagementBean.class, stockManagementBeanDao);
        registerDao(StockManagementDetailsBean.class, stockManagementDetailsBeanDao);
    }
    
    public void clear() {
        commodityPositionGDDaoConfig.clearIdentityScope();
        feedbackBeanDaoConfig.clearIdentityScope();
        goodsDaoConfig.clearIdentityScope();
        mallTypeBeanDaoConfig.clearIdentityScope();
        stockManagementBeanDaoConfig.clearIdentityScope();
        stockManagementDetailsBeanDaoConfig.clearIdentityScope();
    }

    public CommodityPositionGDDao getCommodityPositionGDDao() {
        return commodityPositionGDDao;
    }

    public FeedbackBeanDao getFeedbackBeanDao() {
        return feedbackBeanDao;
    }

    public GoodsDao getGoodsDao() {
        return goodsDao;
    }

    public MallTypeBeanDao getMallTypeBeanDao() {
        return mallTypeBeanDao;
    }

    public StockManagementBeanDao getStockManagementBeanDao() {
        return stockManagementBeanDao;
    }

    public StockManagementDetailsBeanDao getStockManagementDetailsBeanDao() {
        return stockManagementDetailsBeanDao;
    }

}
